name: Deploy Frontend
on:
  push:
    branches:
      - main
env:
  IMAGE: pigutty/react-test
  LOCATION: us
  REPOSITORY: my-container

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: 'actions/checkout@v3' 
    
    - name: authentication
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: github-actions@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0


    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: docker build -t ${{env.IMAGE}} -f Dockerfile.dev .

    - name: tag 
      run: docker tag ${{env.IMAGE}} ${{env.LOCATION}}-docker.pkg.dev/${{secrets.PROJECT_ID}}/${{env.REPOSITORY}}/${{env.IMAGE}}

    - name: push
      run: docker push ${{env.LOCATION}}-docker.pkg.dev/${{secrets.PROJECT_ID}}/${{env.REPOSITORY}}/${{env.IMAGE}}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: 'mycloudrun'
        image: ${{env.LOCATION}}-docker.pkg.dev/${{secrets.PROJECT_ID}}/${{env.REPOSITORY}}/{{env.IMAGE}}

    - name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'